[package]
name = "dedupler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
indicatif = "0.18.0"
ignore = "0.4.23"
chardet = "0.2.4"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"

[dev-dependencies]
tempfile = "3.10.1"